### ISSUE TITLE
Can't run the example command

### ISSUE THREAD

**Issue by toanbku** [Open-Assistant/oasst-model-eval#15]
Hi, following the readme file, I run this command

```python sampling_report.py --model-name facebook/galactica-125m --config config/default.json --prompts data/en_100_text.jsonl --report report_file.json -n 10 --verbose```

and get the error:
```
/opt/conda/envs/python310/lib/python3.10/site-packages/pydantic/_internal/_fields.py:126: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Using pytorch version 2.0.1+cu117
Args: Namespace(device='cuda', device_index=0, model_name='facebook/galactica-125m', mode='legacy', prompts='data/en_100_text.jsonl', report='report_file.json', seed=42, verbose=True, n=10, num_samples=2, config='config/default.json', half=False, int8=False, skip_special_tokens=False, model_type='CausalLM', max_input_len=None, auth_token=None, num_threads=8)
Device: cuda:0
/workspace/oasst-model-eval/model_eval/manual/sampling_report.py:205: PydanticDeprecatedSince20: parse_obj_as is deprecated. Use pydantic.TypeAdapter.validate_python instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.0.2/migration/
  return pydantic.parse_obj_as(Configuration, json_data)
Traceback (most recent call last):
  File "/workspace/oasst-model-eval/model_eval/manual/sampling_report.py", line 357, in <module>
    main()
  File "/workspace/oasst-model-eval/model_eval/manual/sampling_report.py", line 268, in main
    config = load_configs(Path(args.config))
  File "/workspace/oasst-model-eval/model_eval/manual/sampling_report.py", line 205, in load_configs
    return pydantic.parse_obj_as(Configuration, json_data)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/typing_extensions.py", line 2562, in wrapper
    return __arg(*args, **kwargs)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/pydantic/deprecated/tools.py", line 41, in parse_obj_as
    return TypeAdapter(type_).validate_python(obj)
  File "/opt/conda/envs/python310/lib/python3.10/site-packages/pydantic/type_adapter.py", line 192, in validate_python
    return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 16 validation errors for Configuration
default.name
  Field required [type=missing, input_value={'generate_args': {'max_n...d_prefix_tokens': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.0.pre_text
  Field required [type=missing, input_value={'name': 'k50', 'generate...petition_penalty': 1.2}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.0.human_name
  Field required [type=missing, input_value={'name': 'k50', 'generate...petition_penalty': 1.2}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.0.bot_name
  Field required [type=missing, input_value={'name': 'k50', 'generate...petition_penalty': 1.2}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.1.pre_text
  Field required [type=missing, input_value={'name': 'beam5', 'genera...': 0.9, 'num_beams': 5}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.1.human_name
  Field required [type=missing, input_value={'name': 'beam5', 'genera...': 0.9, 'num_beams': 5}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.1.bot_name
  Field required [type=missing, input_value={'name': 'beam5', 'genera...': 0.9, 'num_beams': 5}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.2.pre_text
  Field required [type=missing, input_value={'name': 'magic_numbers',...: 9607, 'top_p': 0.242}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.2.human_name
  Field required [type=missing, input_value={'name': 'magic_numbers',...: 9607, 'top_p': 0.242}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.2.bot_name
  Field required [type=missing, input_value={'name': 'magic_numbers',...: 9607, 'top_p': 0.242}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.3.pre_text
  Field required [type=missing, input_value={'name': 'typical95', 'ge...petition_penalty': 1.2}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.3.human_name
  Field required [type=missing, input_value={'name': 'typical95', 'ge...petition_penalty': 1.2}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.3.bot_name
  Field required [type=missing, input_value={'name': 'typical95', 'ge...petition_penalty': 1.2}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.4.pre_text
  Field required [type=missing, input_value={'name': 'greedy', 'gener... False, 'num_beams': 1}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.4.human_name
  Field required [type=missing, input_value={'name': 'greedy', 'gener... False, 'num_beams': 1}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
configurations.4.bot_name
  Field required [type=missing, input_value={'name': 'greedy', 'gener... False, 'num_beams': 1}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
```

anyone helps me to fix it, thanks

**Comment by toanbku** [comment]
I found the root cause and workaround by locking the version of pydantic at requirements.txt:

```
pydantic==1.9.1
```

Because the latest version of pydantic (v2.0.1) introduces some breaking changes. If we use it, we need to migrate the current code to keep it working: https://docs.pydantic.dev/2.0/migration/

**Comment by andreaskoepf** [comment]
Thanks for the PR! :-)
